### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by tarcisiofischer**
Add support for Windows and re-rendered with conda-smithy 1.7.0

### CODE REVIEW

**Comment by tarcisiofischer** [comment]
cc @nicoddemus

**Comment by nicoddemus** [comment]
LGTM, let's see how it fares on `AppVeyor`.

@tarcisiofischer would mind add me (and you if you want) as `maintainer` of this package? We might want to help update it in the future.

**Comment by jakirkham** [comment]
So I think my Windows install step is wrong. Guessing it should be moved to `%SCRIPTS%`.

**Comment by jakirkham** [comment]
Also please enable CircleCI on your fork of this feedstock and repush.

**Comment by tarcisiofischer** [comment]
So, I tried to make a local build (```conda build waf-feedstock``` in Windows), and it seems that copying the file into the ```%SCRIPTS%``` path will work.

The only problem is that conda-build tries to read the file to do some checking, but fails to do so because of the file encoding (https://github.com/conda/conda-build/blob/master/conda_build/windows.py#L45)

I believe the ```waf``` file should be opened with ```encoding='iso-8859-1'```.
Making a local change replacing with the code bellow builds the package successfully, but is not a solution:

```with open(join(scripts_dir, fn), encoding='iso-8859-1') as f:```

Any suggestions here? I'm unsure how this case should be handled (Or if I should be asking on the ```conda-build``` project)

**Comment by jakirkham** [comment]
Go ahead and raise that as an issue on `conda-build`. Let's see what they say.

**Comment by jakirkham** [comment]
Did you raise an issue with `conda-build`, @tarcisiofischer ? If so, could we have a link to it?

**Comment by jakirkham** [comment]
Just to see, going to toggle this to restart the CIs. `conda-build` 2 is now in use and I'd like to know if this problem persists in this version.

**Comment by jakirkham** [comment]
Also feel free to disable CircleCI on your fork @tarcisiofischer . We recently got CircleCI back online at conda-forge.

**Comment by tarcisiofischer** [comment]
Posted on conda-build. https://github.com/conda/conda-build/issues/1632
Thanks for the help.

**Comment by jakirkham** [comment]
Do you want to give this another go, @tarcisiofischer? `conda-build` 2.1.1 should fix this issue and is out on conda-forge.

**Comment by nicoddemus** [comment]
FWIW just tried in my local installation using @tarcisiofischer's `meta.yaml` and I get what it seems to be the same error:

```
...
   adding waflib\extras\boost.py as waflib/extras/boost.py
   adding waflib\extras\cython.py as waflib/extras/cython.py
   adding waflib\extras\swig.py as waflib/extras/swig.py
   adding waflib\extras\use_config.py as waflib/extras/use_config.py
   adding waflib\extras\__init__.py as waflib/extras/__init__.py
Waf: Leaving directory `D:\Programming\Miniconda3\conda-bld\waf-conda_1484775768299\work\waf-waf-1.8.21\build'
'build' finished successfully (1.023s)

(D:\Programming\Miniconda3\conda-bld\waf-conda_1484775768299\_b_env) %@EXECSTR[python X:\dotfiles\\get_prompt.py]copy waf "D:\Programming\Miniconda3\conda-bld\waf-conda_1484775768299\_b_env\Scripts"
        1 arquivo(s) copiado(s).
Traceback (most recent call last):
  File "D:\Programming\Miniconda3\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "D:\Programming\Miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 321, in main
    execute(sys.argv[1:])
  File "D:\Programming\Miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 312, in execute
    noverify=args.no_verify)
  File "D:\Programming\Miniconda3\lib\site-packages\conda_build\api.py", line 89, in build
    need_source_download=need_source_download, config=config)
  File "D:\Programming\Miniconda3\lib\site-packages\conda_build\build.py", line 1460, in build_tree
    config=config)
  File "D:\Programming\Miniconda3\lib\site-packages\conda_build\build.py", line 1010, in build
    windows.build(m, build_file, config=config)
  File "D:\Programming\Miniconda3\lib\site-packages\conda_build\windows.py", line 233, in build
    fix_staged_scripts(join(config.build_prefix, 'Scripts'))
  File "D:\Programming\Miniconda3\lib\site-packages\conda_build\windows.py", line 47, in fix_staged_scripts
    line = bs4.UnicodeDammit(f.readline()).unicode_markup.lower()
  File "D:\Programming\Miniconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4240: character maps to <undefined>
```

Conda versions:

```
$ conda list conda
# packages in environment at D:\Programming\Miniconda3:
#
anaconda-client           1.5.1                    py35_0    conda-forge
conda                     4.2.13                   py35_0    conda-forge
conda-build               2.1.1                    py35_0    conda-forge
conda-build-all           1.0.0                    py35_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-smithy              2.0.0                    py35_0    conda-forge
conda-verify              2.0.0                    py35_0
```

**Comment by jakirkham** [comment]
Any ideas @msarahan?

**Comment by nicoddemus** [comment]
This has been fixed in `2.1.2` (conda/conda-build#1685).

**Comment by jakirkham** [comment]
Neat! Let's get it packaged. Would you like to do a PR?

ref: https://github.com/conda-forge/conda-build-feedstock

**Comment by nicoddemus** [comment]
Sure thing, done: conda-forge/conda-build-feedstock#11

**Comment by nicoddemus** [comment]
@jakirkham the feedstocks use the latest available `conda-build` in conda-forge, or are they pinned to a specific version? If the former is true, it is just a matter of @tarcisiofischer closing/reopening this PR once conda-forge/conda-build-feedstock#11 is merged.

**Comment by jakirkham** [comment]
Currently we do just use latest. We could open and close to restart. Though Travis CI has been getting pretty slammed during the week. Would propose that we just restart AppVeyor and see how that goes. I expect the patch release didn't break Unix builds, but we could also restart CircleCI as a demonstrative measure. If we restart Travis though, we might be waiting until the end of day to see this merged. Just a thought.

**Comment by nicoddemus** [comment]
Sounds good. Let's see how it goes then.

**Comment by jakirkham** [comment]
Passing. 🎉

**Comment by nicoddemus** [comment]
Cool, thanks @tarcisiofischer and @jakirkham!

**Pull request merged**
