### PR TITLE
MNT: Re-rendered with conda-smithy 2.3.2

### PR DESCRIPTION
**Pull request by dfroger**

### CODE REVIEW

**Comment by dfroger** [comment]
Don't understand what's the problem on circleci, seems not related to this feedstock in particular.

**Comment by nicoddemus** [comment]
Hmm yes it is strange. Perhaps @conda-forge/core has an idea of what's going on?

**Comment by ocefpaf** [comment]
I saw that failure in other places today :confused: 

I just restarted it, finger crossed.

**Comment by dfroger** [comment]
I'll try to merge, and cross finger again...

**Comment by jakirkham** [comment]
Hey everyone, I think CircleCI is having some [issues]( https://status.circleci.com/incidents/sjqp9mkv9m4g ) with Docker. Maybe this will pass once that issue is resolved.

**Comment by nicoddemus** [comment]
Thanks for the update @jakirkham!

**Comment by jakirkham** [comment]
CircleCI has been rolling out a fix for the aforementioned issues. Have tried restarting the latest build on `master` and it seems to be working. Feel free to try restarting any other relevant builds.

**Comment by dfroger** [comment]
@jakirkham thanks!!

**Comment by jakirkham** [comment]
Of course. Looks like those Linux builds are out now.

**Pull request merged**
