### PR TITLE
Update to 2.0.8 and use available artifact (no longer build from source)

### PR DESCRIPTION
**Pull request by nicoddemus**
As commented in:

https://github.com/conda-forge/waf-feedstock/pull/10#issuecomment-386402712

Start to just package the standalone script to make it easy for
conda recipes to use.

### CODE REVIEW

**Comment by nicoddemus** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
> As discussed in https://github.com/waf-project/waf/issues/2158, `waf` developers are not keen on helping here...

That's really quite unfortunate. Am not really sure why they won't help. Especially given it's likely a change on their end that broke things. 😒

> ...but they pointed out that the `waf` distribution is a single file that can be run anywhere.

Hmm...seems to contain some binary stuff at the end. 😕

> Should we start to suggest other feedstocks to download and use the standalone script, or should we instead just build the conda package by downloading the script and putting it into the `bin` folder?

We should really fix the build if possible. Do we have any clue why it fails? 🤔

**Comment by xbreak** [comment]
@jakirkham: The binary stuff at the end is the packaged waf Python libraries. It will unpack itself the first time you execute waf.

Try adding `top='.'` to the wscript as well (see https://waf.io/book/ for examples).

**Comment by nicoddemus** [comment]
Hi @xbreak,

Thanks for joining in.

This has been done as suggested by others already, please see:

https://github.com/conda-forge/waf-feedstock/pull/10/files#diff-aa95511d5ed9348eb09581aa4eaa44a9

Unfortunately that did not work.

Please feel free to provide any other suggestions, I would be glad to try them out.

**Comment by nicoddemus** [comment]
Hi @jakirkham,

> We should really fix the build if possible. Do we have any clue why it fails?

I don't, which is frustrating because it should be a very simple "hello world", so I'm not sure if the problem is in how the package was built or with the "hello world" itself.

**Comment by xbreak** [comment]
I'm not familiar with how conda-forge runs the tests. What does the "workspace" look like and where is it executing waf from? The normal scenario is that you have a waf-project with it's own copy of the waf binary, typically in the root of the project and execute e.g. `waf configure build` from there. Is that what happens in this case?

**Comment by nicoddemus** [comment]
@xbreak thanks for trying to help, we appreciate it.

> What does the "workspace" look like and where is it executing waf from? 

It contains only the `wscript` file.

Here's the full rundown of what happens during the testing stage:

1. Conda creates a brand new environment for testing, containing the recipe run dependencies (just `python` in this case);
1. The `waf` package is installed in the testing environment; here it installs whatever was produced by the package, and we have the `waf` library on `PATH` (`/bin` inside the conda environment);
1. The `wscript` is copied over to an empty directory. Contents:

    ```python
    # simple script to test if waf is working

    top = '.'
    out = 'build'

    def configure(conf):
      print("configure!")

    def build(bld):
      print("build!")
    ```

1. It changes the current working directory to the directory containing the `wscript` file, and executes in order:
    
    - `waf --help`
    - `waf configure`
    - `waf build`

1. The `waf build` command fails with:
  
    ```
    ------> Executing code from the top-level wscript <-----
    Waf: Entering directory `/Users/travis/miniconda3/conda-bld/waf_1525287830147/test_tmp/build'
    [1/1] Creating waf
    -> preparing 'tmp-waf-2.0.7'
    Waf: Leaving directory `/Users/travis/miniconda3/conda-bld/waf_1525287830147/test_tmp/build'
    Build failed
    Traceback (most recent call last):
    File "/Users/travis/miniconda3/conda-bld/waf_1525287830147/_t_env/bin/.waf3-2.0.7-60f9289a061a69c843932288cf51c1f1/waflib/Task.py", line 156, in process
      ret=self.run()
    File "/Users/travis/miniconda3/conda-bld/waf_1525287830147/test_tmp/wscript", line 263, in create_waf
      for k in os.listdir(dd):
    FileNotFoundError: [Errno 2] No such file or directory: 'waflib/.'
    ```

    ([travis logs](https://travis-ci.org/conda-forge/waf-feedstock/builds/374053806?utm_source=github_status&utm_medium=notification|))

I think that's all of it (@jakirkham please correct me if I'm mistaken)

**Comment by xbreak** [comment]
So it was executing the wrong waf? That explains the weird behaviour. It was likely finding the waf sources again and trying to package it a second time, this time without waflib (the output "[1/1] Creating waf" appears in test).

**Comment by nicoddemus** [comment]
> So it was executing the wrong waf? That explains the weird behaviour. 

Can you elaborate? You mean a different `waf` executable than the one that was package? The line below in the traceback seems to indicate it was using the correct waf that was packaged by conda:

```
File "/Users/travis/miniconda3/conda-bld/waf_1525287830147/_t_env/bin/.waf3-2.0.7-60f9289a061a69c843932288cf51c1f1/waflib/Task.py", line 156, in process
```

That's the `waf` binary inside the conda test environment.

**Comment by xbreak** [comment]
I saw that the checks now pass and the difference seems to be this line added:
https://github.com/conda-forge/waf-feedstock/pull/12/files#diff-e178b687b10a71a3348107ae3154e44cR17

The previously failing logs indicate that it was never reading the `wscript` provided by the test, but more likely the `wscript` from the waf sources themselves (it seems likely because of the second `[1/1] Creating waf`). However, it's unclear to me how. You're right though that the executable seems correct.

**Comment by nicoddemus** [comment]
@xbreak sorry, it is unfortunate that we started this discussion here, this only added to the confusion. 

What @jakirkham mentioned in https://github.com/conda-forge/waf-feedstock/pull/12#issuecomment-394616419 was about #11, not this PR.

* #11 tries to build `waf` from *source*, but the testing stage fails.
* #12 (this PR) gives up on trying to build `waf` from *source*, instead we just copy the `waf` artifact directly from https://waf.io/ and package that. This works.

Everything we discussed below https://github.com/conda-forge/waf-feedstock/pull/12#issuecomment-394616419 was about #11, not this PR. Again sorry about this confusion.

**Comment by xbreak** [comment]
Ah, thanks for the clarification. Sorry for adding to the confusion.

**Comment by nicoddemus** [comment]
@xbreak not at all, thanks for trying to help.

**Comment by jakirkham** [comment]
Sorry if my comment caused confusion, was trying to respond to @nicoddemus, but wanted to move the discussion to the active thread. Can see how that was confusing. Sorry about that.

**Comment by jakirkham** [comment]
Think we may have figured it out. Looks like you had all the hard parts in place (would have taken me a bit to figure that out). Took some sleuthing 🕵️ in a local build to find out what was going on. Basically there were two `wscript`s that could get picked up for testing (one from source and one from the recipe) and we end up getting one from source, but we want the recipe one. The error messages generated are basically from this `wscript` from source behaving in an unfamiliar context. Unfortunately the error messages didn't make this particularly clear. Think PR ( https://github.com/conda-forge/waf-feedstock/pull/13 ) fixes this. Though mostly it reuses the existing work you already did. Please let me know what you think.

**Comment by nicoddemus** [comment]
Closed in favor of #13

**Comment by nicoddemus** [comment]
This is awesome, thanks for spending your time on this. 👍

**Pull request closed without merging**
