### PR TITLE
MNT: Re-rendered with conda-smithy 2.1.1

### LINKED ISSUE #5: OSX and py36
There is not package for OSX and Python 3.6 (https://anaconda.org/conda-forge/waf/files).

### PR DESCRIPTION
**Pull request by dfroger**
Hope this will fix #5

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks! Would you like to add yourself as a maintainer?

**Comment by dfroger** [comment]
> Thanks! Would you like to add yourself as a maintainer?

done!

**Comment by jakirkham** [comment]
Thanks guys.

**Comment by nicoddemus** [comment]
Thanks again @dfroger!

**Pull request merged**
